# Usign the Clean Blog theme

title: Numerical Tours
email: gabriel.peyre@ceremade.dauphine.fr
description: > # this means to ignore newlines until "baseurl:"
  Complete Python experiments in mathematical data science, imaging, optimization, learning, and geometry, by Gabriel Peyré and contributors.
baseurl: ""
url: "https://www.numerical-tours.com"
github_username:  gpeyre

plugins: [jekyll-paginate]

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules", "maintenance", "Gemfile", "Gemfile.lock", "README.md", "reports", "vendor"]
